apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-5
  namespace: qos-example
spec:
  containers:

  - name: qos-demo-5-ctr-1
    image: nginx
    resources:
      limits:
        memory: "250Mi"
        cpu: "500m"
      requests:
        memory: "250Mi"
        cpu: "500m"

  - name: qos-demo-5-ctr-2
    image: redis
    resources:
      limits:
        memory: "250Mi"
        cpu: "500m"
      requests:
        memory: "250Mi"
        cpu: "500m"




