name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      Last_Name: ${{ vars.Last_Name }}  # <- Importar variable del repositorio
    steps:
      - name: "Say Hello Carlos it's Monday"
        run: echo "$Greeting $First_Name $Last_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Carlos
