name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Carlos it's Monday"
        run: echo "$Greeiting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Carlos
