name: ProbandoSecretsxd

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      MYPASSWORD: ${{ secrets.MYPASSWORD }}  
    steps:
      - name: "Say Hello Carlos it's Monday"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo "La contraseña secreta es: $MYPASSWORD"
        env:
          First_Name: Carlos
